name: triple
description: Abstraction for the Segmented State Pattern. Use to create Triple Store. 
version: 1.2.0+3
homepage: https://github.com/Flutterando/triple_pattern

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ">=1.3.0 <2.0.0"
  async: ">=2.8.1 <3.0.0"

dev_dependencies:
  test: ^1.16.5
